### ISSUE TITLE
Text Render Issue

### ISSUE THREAD

**Issue by drdm1** [Yooooomi/easy-countdown#5]
Installed via container. Text beneath countdown is overlapped by number countdown.

Can be seen here: https://i.imgur.com/UQNI6ba.png

**Comment by Yooooomi** [comment]
Hello! 
Could you tell me what browser you are using and what are your env values ?

**Comment by drdm1** [comment]
Hi!

I’m using Safari, version 14.0.2. Find attached a screenshot illustrating
the environment variables. There were no adjustments/additions other than
the 'timer' values.

Thanks for the quick response.

**Comment by drdm1** [comment]
As a quick follow up, I just tested using Chrome v.87.0.4280.141 and it
rendered normally. Safari appears to be the culprit.

**Comment by Yooooomi** [comment]
Might be cause of Safari to be honest. I'll have a look tomorrow to see if there are compatibility issues.

**Comment by Yooooomi** [comment]
This should be fixed now. Can you try and keep in touch to know if I can indeed close this issue ?

**Comment by drdm1** [comment]
I can confirm the issue is resolved. Thank you for making this available.
It’s exactly what I was looking for.

Any chance you will be making it more customizable in the future? Font,
size, colour, positioning, etc?

**Comment by Yooooomi** [comment]
Yes I might have a look for more customization in the future. If you feel like you can add something to this project feel free to propose a merge request.
